os: linux
dist: xenial

language: php

jobs:
  include:
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=4.5
      services:
        - mysql
    - php: 7.2
      env: DB=PGSQL CORE_RELEASE=4.5
      services:
        - postgresql
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4.4
      services:
        - mysql
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4.4
      services:
        - mysql

before_script:
  # Init PHP
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-core:"^$CORE_RELEASE"
  - composer require --no-update phpunit/phpunit:^5.7
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:~2.0 --prefer-dist --no-update; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit
