language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4.0

matrix:
  include:
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=4.0
    - php: 7.1
      env: DB=SQLITE3 CORE_RELEASE=4.0

before_script:
  # Init PHP
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  
  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/recipe-core:1.0.x-dev
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.0.x-dev --prefer-dist; fi
  - if [[ $DB == SQLITE ]]; then composer require silverstripe/sqlite3:2.1.x-dev --prefer-dist; fi
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit