language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 5.6
      env: DB=SQLITE3 CORE_RELEASE=3.6
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.5

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require phpunit/php-file-iterator:1.3.4
 - cd ~/builds/ss

script:
 - phpunit sortablegridfield/tests/
